linhas = [
    "# QA Automation Project\n",
    "\n",
    "Projeto de automacao de testes com Python, cobrindo API REST (Petstore Swagger) e Web E2E (SauceDemo), com CI/CD via GitHub Actions.\n",
    "\n",
    "---\n",
    "\n",
    "## Estrutura do Projeto\n",
    "\n",
    "    qa-automation-project/\n",
    "    .github/workflows/ci.yml\n",
    "    api_tests/tests/test_pet.py\n",
    "    api_tests/tests/test_store.py\n",
    "    api_tests/tests/test_user.py\n",
    "    api_tests/utils/api_client.py\n",
    "    api_tests/utils/data_factory.py\n",
    "    web_tests/pages/base_page.py\n",
    "    web_tests/pages/login_page.py\n",
    "    web_tests/pages/inventory_page.py\n",
    "    web_tests/pages/cart_page.py\n",
    "    web_tests/pages/checkout_page.py\n",
    "    web_tests/tests/test_saucedemo.py\n",
    "    web_tests/conftest.py\n",
    "    requirements.txt\n",
    "\n",
    "---\n",
    "\n",
    "## Tecnologias Utilizadas\n",
    "\n",
    "- Python 3.11\n",
    "- pytest\n",
    "- requests\n",
    "- Selenium 4.x\n",
    "- pytest-html\n",
    "- GitHub Actions\n",
    "\n",
    "---\n",
    "\n",
    "## Instalacao e Configuracao\n",
    "\n",
    "1. Clone o repositorio:\n",
    "   git clone https://github.com/seu-usuario/qa-automation-project.git\n",
    "\n",
    "2. Ative o ambiente virtual:\n",
    "   .venv\\Scripts\\activate\n",
    "\n",
    "3. Instale as dependencias:\n",
    "   pip install -r requirements.txt\n",
    "\n",
    "---\n",
    "\n",
    "## Executando os Testes\n",
    "\n",
    "Todos os testes:\n",
    "   pytest\n",
    "\n",
    "Somente API:\n",
    "   pytest api_tests/\n",
    "\n",
    "Somente Web:\n",
    "   pytest web_tests/\n",
    "\n",
    "Com relatorio HTML:\n",
    "   pytest --html=reports/report.html --self-contained-html\n",
    "\n",
    "---\n",
    "\n",
    "## Cobertura dos Testes\n",
    "\n",
    "### API - Petstore Swagger\n",
    "Base URL: https://petstore.swagger.io/v2\n",
    "\n",
    "- Pet: criar, buscar por ID, atualizar, buscar por status, deletar\n",
    "- Store: inventario, realizar pedido, buscar pedido, deletar pedido\n",
    "- User: criar, login, buscar, atualizar, deletar\n",
    "\n",
    "### Web - SauceDemo\n",
    "URL: https://www.saucedemo.com/\n",
    "\n",
    "- Login valido\n",
    "- Login invalido\n",
    "- Fluxo E2E: Login, Produtos, Carrinho, Checkout, Confirmacao\n",
    "\n",
    "---\n",
    "\n",
    "## Pipeline CI/CD - GitHub Actions\n",
    "\n",
    "Acionada em push para main e develop e em Pull Requests.\n",
    "\n",
    "Etapas:\n",
    "1. Checkout do codigo\n",
    "2. Setup Python 3.11\n",
    "3. Instalacao das dependencias\n",
    "4. Testes de API\n",
    "5. Testes Web (Chrome headless)\n",
    "6. Upload do relatorio HTML\n",
    "\n",
    "---\n",
    "\n",
    "## Design Patterns\n",
    "\n",
    "- Page Object Model (POM): cada tela tem sua propria classe\n",
    "- Factory Pattern: data_factory.py centraliza criacao de dados\n",
    "- Base Page: metodos comuns reutilizados por todos os Page Objects\n",
    "- Fixtures: setup e teardown do WebDriver via conftest.py\n",
    "\n",
    "---\n",
    "\n",
    "## Autor\n",
    "\n",
    "Seu Nome\n",
    "Curso de QA\n",
]

with open("README.md", "w", encoding="utf-8") as f:
    f.writelines(linhas)

print("README.md criado com sucesso!")