[pytest]
pythonpath = .
testpaths =
    api_tests/tests
    web_tests/tests

python_files   = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --strict-markers

markers =
    api:   Testes de API REST (Petstore)
    web:   Testes de interface Web (SauceDemo)
    e2e:   Testes de ponta a ponta
    smoke: Testes básicos de sanidade