name: QA Automation — CI Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  api-tests:
    name: "API Tests — Petstore"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Rodar testes de API
        run: pytest api_tests/tests/ -v --tb=short

  web-tests:
    name: "Web E2E Tests — SauceDemo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Instalar Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          chromedriver --version
          chromium-browser --version
      - name: Rodar testes Web
        run: |
          export PATH="/usr/lib/chromium-browser:$PATH"
          pytest web_tests/tests/ -v --tb=short